channels:
  - http://ssb.stsci.edu/astroconda-dev


dependencies:
  - python>=3
  - setuptools  
  - numpy
  - pip:  
    - astropy
    - matplotlib
    - scipy
    - sphinx-automodapi
    - stsci_rtd_theme
    - asdf
    - crds
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - six
    - verhawk
    - sphinx_rtd_theme
