
dependencies:
  - python>=3
  - setuptools
  - matplotlib
  - numpy
  - scipy
  - pip:
    - git+git://github.com/astropy/astropy
    - sphinx-automodapi
    - stsci_rtd_theme
    - asdf
    - crds
    - drizzle
    - gwcs
    - jsonschema
    - jplephem
    - namedlist
    - photutils
    - spherical-geometry
    - stsci.image
    - stsci.imagestats
    - stsci.stimage
    - stsci.tools
    - six
    - verhawk
    - sphinx_rtd_theme
    - Cython>=0.21
    - jinja2>=2.7
    - pyyaml
    - h5py
    - scikit-image
    - pandas
    - pytz
    - beautifulsoup4
    - ipython
    - mpmath
    - matplotlib
    - scipy
    - pillow
    - jplephem
    - sphinx<1.7
    - sphinx-astropy
    - sphinx-gallery
